version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node-modules-volume:/workspace/node_modules

volumes:
  node-modules-volume:
